In [1]:
import numpy as np
import h5py

In [2]:
# This the data segment
data = np.arange(10)

# Show what the 'data' is
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Create a hdf5 file object
## haha
f = h5py.File("demo.hdf5", "w")

# Show what f is
f

# Some suspiciously looking named items here, like
# - f.iterkeys
# - f.iteritems
# - f.keys
# - ...
# These are things that you would find in python dictionaries
# First piece of information on how HDF file interface works:
# This container objects (files and groups) work like python dictionaries

<HDF5 file "demo.hdf5" (mode r+)>

In [4]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Assign data to 'mydata'
f['mydata'] = data

In [8]:
# This is a a proxy object
# Allows partial I/O & attribute access
dset = f['mydata']
dset

<HDF5 dataset "mydata": shape (10,), type "<i8">

In [9]:
# Investigating this object further
# Data shape (just a like a numpy array)
dset.shape

(10,)

In [10]:
# Data type (just a like a numpy array)
dset.dtype

dtype('int64')

In [11]:
# Access the array itself (numpy syntax)
dset[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Supports partial I/O
# Numpy slicing syntax
# uses HDF5 capabilities, only reads these entries
# very efficient for large datasets
dset[0:6:2]

array([0, 2, 4])

In [18]:
# In numpy you can specify which indeces you want
# HDF only pulls out these elements
data[[0,2,6]]

array([0, 2, 6])

In [17]:
# In numpy you can specify which indeces you want
# HDF only pulls out these elements
dset[[1,2,6]]

array([1, 2, 6])

In [31]:
# Attributes of our object
# Behaves like python dictionaries
dset.attrs

<Attributes of HDF5 object at 140547503593296>

In [25]:
# Add a metadata
dset.attrs['sampling rate'] = 100e6 # sampling rate
dset.attrs['pressure'] = 15 # pressure

In [26]:
dset.attrs.keys()


KeysView(<Attributes of HDF5 object at 140547503593296>)

In [27]:
dset.attrs.items()

ItemsViewHDF5(<Attributes of HDF5 object at 140547503593296>)

In [28]:
list(dset.attrs)

['sampling rate', 'pressure']

In [29]:
dset.attrs.items()

ItemsViewHDF5(<Attributes of HDF5 object at 140547503593296>)

In [30]:
list(dset.attrs.items())

[('sampling rate', 100000000.0), ('pressure', 15)]

In [32]:
f.close()